apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kuwc45ekt-nodejs
  janus-idp.io/tekton: kuwc45ekt-nodejs
  backstage.io/kubernetes-id: kuwc45ekt-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kuwc45ekt-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
